# Build information from workflow inputs
luajava.branch=v4.0.2
redis.branch=8.2.2
version=1.1.0-SNAPSHOT
maven.group.id=org.infinispan
skip.publish=true

# Build metadata
github.workflow=Create Source Artifact
github.run.id=23008566897
github.run.number=104
github.actor=rigazilla
github.ref=refs/heads/main
github.sha=8266d050917c1a6d6829e6067a97ba85d48616d4
build.timestamp=2026-03-12T15:02:20Z
