# Build information from workflow inputs
luajava.branch=v4.0.2
redis.branch=8.2.2
version=1.1.0-SNAPSHOT
maven.group.id=org.infinispan
skip.publish=true

# Build metadata
github.workflow=Create Source Artifact
github.run.id=23004609026
github.run.number=103
github.actor=rigazilla
github.ref=refs/heads/main
github.sha=7b344d7e5368fd1fc4d8cffcbd42c824c0f1b5bb
build.timestamp=2026-03-12T13:35:14Z
