# Build information from workflow inputs
luajava.branch=v4.0.2
redis.branch=8.2.2
version=1.1.0-SNAPSHOT
maven.group.id=org.infinispan
skip.publish=true

# Build metadata
github.workflow=Create Source Artifact
github.run.id=23049067272
github.run.number=105
github.actor=rigazilla
github.ref=refs/heads/main
github.sha=67d810e010c111c1af23b529a39911af3d63f878
build.timestamp=2026-03-13T11:37:03Z
